name: Docs to PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**.md'
      - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: website-v2/static
          images_dir: docs/assets
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: website-v2/static

